openapi: 3.0.0
info:
  title: SiTerbang API
  description: SiTerbang API Documentation
  version: 0.0.1

servers:
  - url: http://localhost:3000
    description: Localhost
  - url: https://siterbang-api-test.km3ggwp.com
    desription: Deployment on railway

tags:
  - Auth
  - Airplanes
  - Airlines
  - Product
  - User

paths:
  /auth/register:
    post:
      summary: Register New Account
      description: Register New Account For Buyer
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                confirm_password:
                  type: string
            examples:
              example-body:
                value:
                  name: John Doe
                  email: johndoe@mail.com
                  password: admin123
                  confirm_password: admin123
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                      email:
                        type: string
                        format: email
                      password:
                        type: string
              examples:
                regist-user:
                  value:
                    status: true
                    message: Register success
                    data:
                      name: John Doe
                      email: johndoe@mail.com
                      password: admin123
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
              examples:
                doesn't-match-password:
                  value:
                    status: false
                    message: Password doesn't match
                    data: null
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
              examples:
                email-exist:
                  value:
                    status: false
                    message: Email already exist
                    data: null
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  /auth/login:
    post:
      summary: Login Account
      description: Login Account
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
            exampless:
              login-examples:
                value:
                  email: johndoe@gmail.com
                  password: admin123
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      email:
                        type: string
                      token:
                        type: string
              examples:
                status-example:
                  value:
                    status: true
                    message: login success
                    data:
                      email: johndoe@gmail.com
                      token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJkZWRlbnNldHlhd2FuMTdAZ21haWwuY29tIiwicm9sZSI6IkJVWUVSIiwiaWF0IjoxNjY5NDYwNTg0LCJleHAiOjE2Njk0NjQxODR9.UpEBOEZ4sVQfWhtzsdcJRUoJyROBVl8z6W528rMtYaY
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  /auth/google:
    post:
      summary: Login or Register Google
      description: Login or Register With Google
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                access_token:
                  type: string
            examples:
              example-body:
                value:
                  access_token: "ya29.a0AX9GBdVioT6WPTHQp_k75q1enKbSqBaR-f936Jdysoyij--_0Siod3SnsyMz73t15zjOxRzDpCf_I8IQ4y-G4q0Phoy9EO9qIbPFsnSR0m0ugTRsO6irrvtqFrYM3nXPbYELMliv20KPUrhAu4lUdxG19BTuaCgYKASsSARESFQHUCsbCPYMDsvqdITSHMSeLMqToJg0163"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      email:
                        type: string
                      role:
                        type: string
                      token:
                        type: string
              examples:
                status-ok:
                  value:
                    status: true
                    message: "success"
                    data:
                      email: "johndoe@gmail.com"
                      role: "GOOGLE"
                      token: ""
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /auth/get:
    get:
      summary: Get All User
      description: Gell All User
      tags:
        - Auth
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      email:
                        type: string
                      emailToken:
                        type: string
                      password:
                        type: string
                      phone:
                        type: string
                      gender:
                        type: string
                      address:
                        type: string
                      postal_code:
                        type: string
                      photo:
                        type: string
                      is_verified:
                        type: string
                      user_type:
                        type: string
                      role:
                        type: string
                      token:
                        type: string
  /auth/forgot-password:
    post:
      summary: Forgot Password Account
      description: Request Forgot Password Account Via Email
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
            examples:
              example-body:
                value:
                  email: johndoe@mail.com
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                  properties:
                    status:
                      type: boolean
                    message:
                      type: string
                    data:
                      type: object
                      properties:
                        email:
                          type: string
              examples:
                forgot-password:
                  value:
                    status: true
                    message: request forgot-password successful
                    data:
                      email: johndoe@gmail.com
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  /auth/reset-password/{token}:
    post:
      summary: Reset Password
      description: Reset Password Account
      tags: 
        - Auth
      parameters:
        - schema:
            type: string
          in: query
          name: token
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                confirm_password:
                  type: string
            examples:
              reset-password:
                password: admin123
                confirm_password: admin123
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
              examples:
                succesfull:
                  value:
                    status: true
                    message: Update Password Success
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
              examples:
                password-doesn't-match:
                  value:
                    status: false
                    message: Password Doesn't Match
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
              examples:
                unauthorized:
                  value:
                    status: false
                    message: invalid token
        '500':
          description: Internal Service Error
  /user:
    get:
      summary: Get User Info Profile
      description: Get An User Info Profile
      tags:
        - User
      # parameters:
      #   - name: authorization
      #     in: header
      #     schema:
      #       type: string
      #     required: true 
      security:
        bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                      email:
                        type: string
                      phone:
                        type: string
                      gender:
                        type: string
                      postal_code:
                        type: integer
                      address:
                        type: string
                      photo:
                        type: string
              examples:
                status-ok:
                  value:
                    name: "John Doe"
                    email: "johdoe@mail.com"
                    phone: "36728944839279"
                    gender: "male"
                    postal_code: 153671
                    address: "Jakarta"
                    photo: "https://imagekit.io/asgdjawgy"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '500':
          description: Internal Server Error
  /user/profile:
    put:
      summary: Update An User Profile
      description: Update An User Profile
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                gender:
                  type: string
                postal_code:
                  type: integer
                address:
                  type: string
            examples:
              example-body:
                value:
                  name: "John Doe"
                  email: "johdoe@mail.com"
                  phone: "36728944839279"
                  gender: "male"
                  postal_code: 153671
                  address: "Jakarta"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                      email:
                        type: string
                      phone:
                        type: string
                      gender:
                        type: string
                      postal_code:
                        type: integer
                      address:
                        type: string
                      photo:
                        type: string
              examples:
                status-ok:
                  value:
                    status: true
                    message: "Success"
                    data:
                      name: "John Doe"
                      email: "johdoe@mail.com"
                      phone: "36728944839279"
                      gender: "male"
                      postal_code: 153671
                      address: "Bandung"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '500':
          description: Internal Server Error
  /user/profile/photo:
    put:
      summary: Update An Photo User Profile
      description: Update An Photo For User
      tags:
        - User
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                photo:
                  type: string
                  format: binary
          description: "Only png, jpg, and jpeg allowed to upload"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      photo:
                        type: string
              examples:
                status-ok:
                  value:
                    photo: "https://imagekit.io/asgdjawgy"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '500':
          description: Internal Server Error
  /user/profile/change-password:
    put:
      summary: Update Password User
      description: Update An Password User Profile
      tags:
        - User
      security:
        bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                old_password:
                  type: string
                new_password:
                  type: string
                confirm_new_password:
                  type: string
            examples:
              example-body:
                value:
                  old_password: "admin123"
                  new_password: "123admin"
                  confirm_new_password: "123admin"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
              examples:
                status-ok:
                  value:
                    status: true
                    message: "Success"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data: null
              examples:
                status-badrequest:
                  value:
                    status: false
                    message: "Minimum Password is 8 character"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
              examples:
                status-unauthorized:
                  value:
                    status: false
                    message: "You're not authorized || Wrong Password || Password doesn't match"
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '500':
          description: Internal Server Error  
  /airlines:
    get:
      summary: Get All Airlines By Search
      description:
      tags:
        - Airlines
      security:
        - bearerAuth: []
      parameters:
        # - name: Authorization
        #   in: header
        #   schema:
        #     type: string
        #   example: "{{token}}"
        - name: Search
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: booelan
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      status:
                        type: boolean
                      message:
                        type: string
                      data:
                        type: object
                        properties:
                          name:
                            type: string
                          phone:
                            type: string
              examples:
                status-ok:
                  value:
                    status: true
                    message: "Success"
                    data:
                      name: "Garuda Indonesia"
                      phone: "086736247823"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '500':
          description: Internal Server Error
    post:
      summary: Create Airline
      description: Create An Airline
      tags:
        - Airlines
      security:
        bearerAuth: []
      # parameters:
      #   - name: Authorization
      #     in: header
      #     schema:
      #       type: string
      #     example: "{{token}}"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                phone:
                  type: string
            examples:
              example-body:
                value:
                  name: "Citilink"
                  phone: "081235761"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                      phone:
                        type: string
              examples:
                status-ok:
                  value:
                    status: true
                    message: "success"
                    data:
                      name: "Citilink"
                      phone: "081235761"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '500':
          description: Internal Server Error
  /airlines/all:
    get:
      summary: Get All Airlines
      description: Get All Airlines
      tags:
        - Airlines
      # parameters:
      #   - name: Authorization
      #     in: header
      #     schema:
      #       type: string
      #     example: "{{token}}"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                      phone:
                        type: string
      '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
      '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
      '500':
          description: Internal Server Error
  /airlines/{id}:
    get:
      summary: Get Airlines By Id
      description: Get An Airlines By Id
      tags:
        - Airlines
      parameters:
        # - name: Authorization
        #   in: header
        #   schema:
        #     type: string
        #   example: "{{token}}"
        - name: id
          in: path
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                      phone:
                        type: string
              examples:
                status-ok:
                  value:
                    status: true
                    message: "sucess"
                    data:
                      name: "Citilink"
                      phone: "0816257218"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '500':
          description: Internal Server Error
    put:
      summary: Update Airline By Id
      description: Update An Airline By Id
      tags:
        - Airlines
      parameters:
        # - name: Authorization
        #   in: header
        #   schema:
        #     type: string
        #   example: "{{token}}"
        - name: id
          in: path
          schema:
            type: integer
          example: 1
          required: true 
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                phone:
                  type: string
            examples:
              example-body:
                value:
                  name: "Garuda Indonesia"
                  phone: "8092714343"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                      phone:
                        type: string
              examples:
                status-ok:
                  value:
                    status: true
                    message: "Success"
                    data:
                      name: "Garuda Indonesia"
                      phone: "930274375323"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '500':
          description: Internal Server Error
    delete:
      summary: Delete Airlines By Id
      description: Delete An Airlines By Id
      tags:
        - Airlines
      security:
        bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          example: 1
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message: string
                    type: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                      phone:
                        type: string
              examples:
                status-ok:
                  value:
                    status: true
                    message: "Success"
                    data:
                      name: "Garuda Indonesia"
                      phone: "90742394678"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '500':
          description: Internal Server Error
  /airplanes:
    get:
      summary: Get All Airplanes
      description: Get All Airplanes
      tags:
        - Airplanes
      security:
        bearerAuth: []
      parameters:
        - name: search
          in: query
          schema:
            type: string
          required: true 
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                      airline_id:
                        type: integer
                      tipe:
                        type: string
                      capacity:
                        type: integer
              examples:
                status-ok:
                  value:
                    status: true 
                    message: "Success"
                    data:
                      name: "Garuda Indonesia"
                      airline_id: 1
                      type: "BOEING 7777"
                      capacity: 200
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '500':
          description: Internal Server Error
    post:
      summary: Create An Airplane
      description: Create An Airplane
      tags:
        - Airplanes
      security:
        bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                airline_id:
                  type: integer
                tipe:
                  type: string
                capacity:
                  type: integer
            examples:
              example-body:
                value:
                  name: "Garuda Indonesia"
                  airline_id: 1
                  type: "BOEING 7777"
                  capacity: 200
      responses:
        '200':
          description: OK
          content:
            applicatioon/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                      airline_id:
                        type: integer
                      tipe:
                        type: string
                      capacity:
                        type: integer
              examples:
                status-ok:
                  value:
                    status: true
                    message: "Success"
                    data:
                      name: "Garuda Indonesia"
                      airline_id: 1
                      type: "BOEING 7777"
                      capacity: 200
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
              examples:
                status-conflict:
                  value:
                    status: false 
                    message: "Airplane already exist"
                    data: null 
        '500':
          description: Internal Server Error
  /airplanes/{id}:
    get:
      summary: Get An Airplane By Id
      description: Get An Airplane By Id
      tags:
        - Airplanes
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true 
          examples: 1
      security:
        bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                      airline_id:
                        type: integer
                      tipe:
                        type: string
                      capacity:
                        type: integer
              examples:
                status-ok:
                  value:
                    status: true
                    message: "Success"
                    data:
                      name: "Garuda Indonesia"
                      airline_id: 1
                      type: "BOEING 7777"
                      capacity: 200
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
              examples:
                status-unauthorized:
                  value:
                    status: false 
                    message: "You're not authorized"
                    data: null 
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '500':
          description: Internal Server Error
    put:
      summary: Update An Airplane By Id
      description: Update An Airplane By Id
      tags:
        - Airplanes
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true 
          examples: 1
      security:
        bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                airline_id:
                  type: integer
                tipe:
                  type: string
                capacity:
                  type: integer
            examples:
              example-body:
                value:
                  name: "Garuda Indonesia"
                  airline_id: 1
                  type: "BOEING 7777"
                  capacity: 200
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                      airline_id:
                        type: integer
                      tipe:
                        type: string
                      capacity:
                        type: integer
              examples:
                status-ok:
                  value:
                    status: true
                    message: "Success"
                    data:
                      name: "Garuda Indonesia"
                      airline_id: 1
                      type: "BOEING 7777"
                      capacity: 200
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
              examples:
                status-unauthorized:
                  value:
                    status: false 
                    message: "You're not authorized"
                    data: null 
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '500':
          description: Internal Server Error
    delete:
      summary: Delete An Airplane By Id
      description: Delete An Airplane By Id
      tags:
        - Airplanes
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true 
          examples: 1
      security:
        bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                      airline_id:
                        type: integer
                      tipe:
                        type: string
                      capacity:
                        type: integer
              examples:
                status-ok:
                  value:
                    status: true
                    message: "Success"
                    data:
                      name: "Garuda Indonesia"
                      airline_id: 1
                      type: "BOEING 7777"
                      capacity: 200
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
              examples:
                status-unauthorized:
                  value:
                    status: false 
                    message: "You're not authorized"
                    data: null 
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '500':
          description: Internal Server Error
  /airplanes/all:
    get:
      summary: Get All Airplanes
      description: Get All Airplanes
      tags:
        - Airplanes
      security:
        bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                      airline_id:
                        type: integer
                      tipe:
                        type: string
                      capacity:
                        type: integer
              examples:
                status-ok:
                  value:
                    status: true
                    message: "Success"
                    data:
                      name: "Garuda Indonesia"
                      airline_id: 1
                      type: "BOEING 7777"
                      capacity: 200
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
              examples:
                status-unauthorized:
                  value:
                    status: false 
                    message: "You're not authorized"
                    data: null 
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '500':
          description: Internal Server Error
  /airports:
    get:
      summary: Get An Airport By Search
      description: Get An Airport By Search
      tags:
        - Airports
      parameters:
        - name: Search
          in: query
          schema:
            type: string
          required: true
      security:
        bearerAuth: []
      responses:
        '200':
          decsription: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      iata_code:
                        type: string
                      name:
                        type: string
                      city:
                        type: string
                      country:
                        type: string
              example:
                status-ok:
                  value:
                    status:
                      type: string
                    message:
                      type: string
                    data:
                      type: object
                      properties:
                        iata_code:
                          type: string
                        name:
                          type: string
                        city:
                          type: string
                        country:
                          type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
              examples:
                status-unauthorized:
                  value:
                    status: false 
                    message: "You're not authorized"
                    data: null 
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '500':
          description: Internal Server Error
    post:
      summary: Create An Airports
      description: Create An Airports
      tags:
        - Airports
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                iata_code:
                  type: string
                name:
                  type: string
                city:
                  type: string
                country:
                  type: string
            examples:
              example-body:
                value:
                  iata_code: "CGK"
                  name: "Soekarno-Hatta"
                  city: "Jakarta"
                  country: "Indonesia"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      iata_code:
                        type: string
                      name:
                        type: string
                      city:
                        type: string
                      country:
                        type: string
              examples:
                example-body:
                  value:
                    status: true
                    message: "Success"
                    data:
                      iata_code: "CGK"
                      name: "Soekarno-Hatta"
                      city: "Jakarta"
                      country: "Indonesia"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
              examples:
                status-unauthorized:
                  value:
                    status: false 
                    message: "You're not authorized"
                    data: null 
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data: null
        '500':
          description: Internal Server Error
  /airports/all:
    get:
      summary: Get All Airports
      description: Get All Airports
      tags:
        - Airports
      security:
        bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      iata_code:
                        type: string
                      name:
                        type: string
                      city:
                        type: string
                      country:
                        type: string
              examples:
                status-ok:
                  value:
                    status:
                      type: boolean
                    message:
                      type: string
                    data:
                      type: object
                      properties:
                        
                        
      
    
                        


                  



  

  
    



                      
    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                
      
      
                        


                      
components:
  schemas: {}
  securitySchemes:
    bearerAuth:            # arbitrary name for the security schema
      type: http
      scheme: bearer